In [12]:
#importing pandas and loading the data.
import pandas as pd
pumpkins=pd.read_csv('../data/US-pumpkins.csv')

In [13]:
pumpkins = pumpkins[pumpkins['Package'].str.contains('bushel', case=True, regex=True)]

In [14]:
#checking the data
print(pumpkins.shape)
pumpkins.isnull().sum()

(415, 26)

City Name            0
Type               406
Package              0
Variety              0
Sub Variety        167
Grade              415
Date                 0
Low Price            0
High Price           0
Mostly Low          24
Mostly High         24
Origin               0
Origin District    396
Item Size          114
Color              145
Environment        415
Unit of Sale       404
Quality            415
Condition          415
Appearance         415
Storage            415
Crop               415
Repack               0
Trans Mode         415
Unnamed: 24        415
Unnamed: 25        391
dtype: int64

In [15]:
pumpkins.sample(5)

,City Name,Type,Package,Variety,Sub Variety,Grade,Date,Low Price,High Price,Mostly Low,...,Unit of Sale,Quality,Condition,Appearance,Storage,Crop,Repack,Trans Mode,Unnamed: 24,Unnamed: 25
1535,SAN FRANCISCO,NaN,1/2 bushel cartons,MINIATURE,FLAT TYPE,NaN,10/1/16,20.0,20.0,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN
1022,COLUMBIA,NaN,1/2 bushel cartons,MINIATURE,FLAT TYPE,NaN,10/1/16,18.0,18.0,18.0,...,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN
714,CHICAGO,Organic,1 1/9 bushel cartons,PIE TYPE,NaN,NaN,10/29/16,22.5,22.5,22.5,...,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN
542,BOSTON,NaN,1/2 bushel cartons,MINIATURE,FLAT TYPE,NaN,10/22/16,15.0,18.0,15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN
1246,NEW YORK,NaN,1 1/9 bushel crates,MINIATURE,ROUND TYPE,NaN,10/15/16,18.0,18.0,18.0,...,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN

In [16]:
pumpkins.Date.sample(15)

1575     9/23/17
791     10/29/16
674      10/8/16
1230    10/29/16
149      9/30/17
982     10/29/16
1723     9/27/16
1742     9/30/16
1626    10/22/16
392     10/22/16
798     11/12/16
1629     9/16/17
362      11/5/16
1643     10/1/16
806       9/9/17
Name: Date, dtype: str

In [17]:
#selecting ont the needed columns using loc which is non-index based selection.
pumpkins=pumpkins.loc[:,["Package","Low Price","High Price","Date"]]
pumpkins.shape

(415, 4)

In [45]:
#changing the data acc to our need.
avgprice = (pumpkins['Low Price'] + pumpkins['High Price'])/2
print(len(avgprice))
pumpkins['Date']=pd.to_datetime(pumpkins['Date'],format='mixed')
month=pd.DatetimeIndex(pumpkins['Date']).month

415

In [46]:
#new dataframe
new_pumpkins=pd.DataFrame({'Month': month,'Package':pumpkins['Package'],'Low Price':pumpkins['Low Price']
                           ,'High Price': pumpkins['High Price'],'Avg Price':avgprice})

new_pumpkins.loc[new_pumpkins['Package'].str.contains('1 1/9'), 'Avg Price'] = avgprice/(1 + 1/9)

new_pumpkins.loc[new_pumpkins['Package'].str.contains('1/2'), 'Avg Price'] = avgprice/(1/2)


new_pumpkins.head(5)

    Month               Package  Low Price  High Price  Avg Price
70      1  1 1/9 bushel cartons       15.0        15.0       13.5
71      1  1 1/9 bushel cartons       18.0        18.0       16.2
72      1  1 1/9 bushel cartons       18.0        18.0       16.2
73      1  1 1/9 bushel cartons       17.0        17.0       15.3
74      1  1 1/9 bushel cartons       15.0        15.0       13.5